# Generated by Django 3.2.6 on 2022-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=800, null=True)),
                ('email', models.EmailField(max_length=500)),
                ('telephone', models.IntegerField()),
                ('niveau_etude', models.CharField(max_length=500)),
                ('centre_souhaite', models.CharField(max_length=500)),
                ('formation_souhaitee', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
